### ISSUE TITLE
Fail to install FeitCSI-iwlwifi in either ways

### ISSUE THREAD

**Issue by Precious1101** [KuskoSoft/FeitCSI#1]
Hi @KuskoSoft  , thanks for the excellent work.
My Linux OS is Ubuntu 22.04.4LTS (desktop-amd64), installed on real hardware. Just newly installed.
>  $ uname -r
 6.5.0-28-generic

When I install from source:
![make_fail](https://github.com/KuskoSoft/FeitCSI/assets/65907461/1410bc34-53c6-499d-9dbc-3831ff2828f7)

Then I turn to install with .deb package:
I put .deb file in /home/(user)/feitcsi-iwlwifi_1.1.0_all.deb but got ``dpkg error``  and  ``(13: Permission denied)``:
![_apt_fail](https://github.com/KuskoSoft/FeitCSI/assets/65907461/4c4b55aa-243a-4f5a-87cb-ca4cc89fdf46)

so I put .deb file to /tmp/feitcsi-iwlwifi_1.1.0_all.deb but the ``dpkg error`` still exists:
![deb_fail](https://github.com/KuskoSoft/FeitCSI/assets/65907461/f09f9891-ba08-4c22-b911-940cadf029e3)
I tried
>  $ sudo apt-get -f install ./feitcsi-iwlwifi_1.1.0_all.deb

as well as

>  $ sudo dpkg -i /tmp/feitcsi-iwlwifi_1.1.0_all.deb

both return the same ``dpkg error``. force overwrite also failed.

![Screenshot from 2024-04-19 17-23-30](https://github.com/KuskoSoft/FeitCSI/assets/65907461/fc49e370-7166-4681-a186-c4ee45ded46d)
![Screenshot from 2024-04-19 18-47-43](https://github.com/KuskoSoft/FeitCSI/assets/65907461/2edb1933-b832-4ad0-be42-b72e9b80f940)
Seems I encountered the same problem as ``install from source``.

I retried on Ubuntu 20.04.6 and Ubuntu 23.10.1, unfortunately same thing happened.

 What's wrong with my installation? Thanks for your reply!

**Comment by KuskoSoft** [comment]
Hello @Precious1101 , based on first screenshot after command `make defconfig-iwlwifi-public` you get `lex: no such file or directory`.  It seems that flex is dependency for make configuration file. Install it with `sudo apt install flex` and then installation from source should work and also .deb.

Regards to installation from .deb package and force overwrite, I have to fix it to not install these files if already exist.

So try to install flex and the feitcsi. Let me then know if all works. Thank you.

**Comment by Precious1101** [comment]
Hi @KuskoSoft , ``sudo apt install flex`` solves ``lex: no such file or directory`` but next comes ``yacc: no such file or directory`` so ``sudo apt install yacc``. 
Then another error happend: 
![Screenshot from 2024-04-20 23-46-48](https://github.com/KuskoSoft/FeitCSI/assets/65907461/f3c8ca08-9bc0-4e8c-9b3a-6e54a5196dd1)
![Screenshot from 2024-04-21 00-01-59](https://github.com/KuskoSoft/FeitCSI/assets/65907461/a3d631a9-811e-4cdd-b324-70874be6e4af)
![Screenshot from 2024-04-21 00-00-10](https://github.com/KuskoSoft/FeitCSI/assets/65907461/080a7955-4b6e-4cb3-9fd9-85e9956f7923)

**Comment by KuskoSoft** [comment]
I install 22.04.4LTS and tried to reproduce your problem but everything works for me. I just install `sudo apt install flex bison` (lex, yacc problems).

![feitcsi-defconfig](https://github.com/KuskoSoft/FeitCSI/assets/40988390/8c2832c6-45e6-4ab3-b4c9-82c22aa044cb)

If you didn't tried before, delete feitcsi, clone again and remove also .debs (`sudo apt purge feitcsi*`) and tried to again. There is problem with generating config file and I really don't know where. I didn't encountered with this problem before and I installed on multiple devices and different architectures.

**Comment by Precious1101** [comment]
Hi @KuskoSoft . Thanks for the advice, now it works!
Two more things:
1. When I measure from GUI, the maximum receiving rate is always less than 30 packets/seconds when from another PC --inject-delay is much smaller than 33.3ms.
But when I measure from command line, --plot shows a much faster update that is consistent with the injection rate.
2. The highest frequency it can reach is 5825MHz, any value higher than it returns either ``kernel reports: Channel is disabled (newline) : iostream error``(such as 6025MHz) or ``command failed: Input/output error-5  (newline) : iostream error``(such as 6015MHz). 
But Ax210 should have access to 6GHz.

These two happen on both my PC and laptop. Do you have any idea?

**Comment by Precious1101** [comment]
Sure @KuskoSoft ,
on 22.04.4:

> nats@nats-pc: ~ $ sudo dmesg | grep "iwlwifi-"
(returns nothing)
> nats@nats-pc: ~ $ sudo dmesg | grep "iwlwifi"
[   10.406752] Loading modules backported from iwlwifi
[   10.406754] FeitCSI-iwlwifi 1.1.0
...
[   14.399967] iwlwifi 0000:04:00.0: loaded firmware version 86.fb5c9aeb.0 ty-a0-gf-a0-86.ucode op_mode iwlmvm
...

on 23.10.1:

**Comment by Precious1101** [comment]
Hi @KuskoSoft ,
I update from source on my PC (Ubuntu 22.04.4) (new version FeitCSI), and laptop (Ubuntu 23.10.1) not updated (old version FeitCSI),

1. 
- New version FeitCSI now ``receives`` (not --plot or --gui) all the packets consistent with inject rate (I tested --inject-delay 1ms). However, on both ``--plot`` and ``--gui``, on 20MHz HT updates normally, but 160MHz HESU updates very, very slow.
- Old version FeitCSI: ``receives`` packets at a non-fixed rate and not all packets received (besides, larger BW, fewer packets). But ``--plot`` updates very, very fast (even at 160MHz HESU --inject-delay 1ms) and ``--gui`` updates figures fast (not as fast as ``--plot`).
- I guess new FeitCSI makes tradeoff. I agree on the priority of receiving packets. I think there is still room for improvement (I tested on PicoScenes it can in time ``receive`` 160MHz packets and meanwhile ``--plot`` synchronously).

**Comment by KuskoSoft** [comment]
Hello @Precious1101 , sorry for late response but I am busy these days.

1. The problem was how I handle gnuplot via pipes. Sending data was very slow especially with more CSI data. I tried to change it to make gnuplot load from a file but problem was flickering of the plot. So I looking for some public light library for GTK but I dont find any easy and lightweight. So in the end I decided to code simple line chart and draw it using cairo. So dependency on gnuplot is gone and plotting is now fast also with 160 MHz and HESU (should be equal to refresh rate of monitor).

2. This is weird because there is no information about that channel is disabled. if I look correct in old version it works. There is no error. But driver version not change. Maybe something just went wrong.. Can you try clean install of FeitCSI? Then look `sudo modinfo iwlmvm` if version of iwlwifi is feitcsi and try again `sudo feitcsi --frequency 6035 --channel-width 20 --format HESU --output-file csi.dat -v`.  If you will have still problem please give me output of `sudo iw reg get`.

Thank you for your patience!

**Comment by Precious1101** [comment]
@KuskoSoft I ``sudo rm -r /usr/local/bin/feitcsi``, ``sudo rm -r  /home/(username)/FeitCSI``, and reinstall FeitCSI from source. Here is the output:
![Screenshot from 2024-05-03 13-18-57](https://github.com/KuskoSoft/FeitCSI/assets/65907461/5d2d7709-878b-4919-8e02-c60970e533f4)

**Comment by KuskoSoft** [comment]
Hi @Precious1101 , output looks good. You wrote that you used 6GHz before just to be sure please check it again `sudo lspci` if you really have AX210.

Because FeitCSI fail to set 6GHz please try it with command `iw`. First check your devices `sudo iw dev`. If there is no monitor device add it `sudo iw phy phy1 interface add mon0 type monitor`  with your phy device. Delete your previous device `sudo iw dev wlan0 del`, enable monitor device `sudo ip link set mon0 up` and then set frequency `sudo iw dev mon0 set freq 6035 20`.  In the end check `sudo iw dev` and you should see frequency 6035 MHz. If command with set frequency fail probably is problem with hardware. 

The last option which you can try is use [FeitCSI ISO with virtual manager](https://feitcsi.kuskosoft.com./virt_manager/). If it also fail, my conclusion is that problem is in the hardware.

**Comment by Precious1101** [comment]
Hi @KuskoSoft , seems the command with set frequency fails, this happens to my both devices.
> $ sudo iw dev mon0 set freq 6035 20
command failed: Input/output error (-5)

![Screenshot from 2024-05-09 18-23-07](https://github.com/KuskoSoft/FeitCSI/assets/65907461/0dd100e1-b26a-4c08-8a3b-4c70526b920e)
![Screenshot from 2024-05-09 18-22-21](https://github.com/KuskoSoft/FeitCSI/assets/65907461/f9d2cdef-cbca-4558-87bd-197f5f3926ce)

**Comment by KuskoSoft** [comment]
Hello @Precious1101 , thank you for your response. So the problem have to be somewhere else. So let me know if you figure it out something. Thank you!

Btw this is output of my `lspci`. It shows **Wi-Fi 6E**, yours showing only **Wi-Fi 6** what is weird. I think all AX210 support also 6E.
![image](https://github.com/KuskoSoft/FeitCSI/assets/40988390/21721644-1859-4bee-b80a-424db49df2a4)
