### ISSUE TITLE
Recommended Hardwares

### ISSUE THREAD

**Issue by HeyGF** [KuskoSoft/FeitCSI#3]
Hello @KuskoSoft, thanks for the wonderful tool! I was wondering do you have some recommendations for the hardware like the computers/devices with PCI/PCIe and NIC cards you've tested on? 

Besides, will Raspberry with these setting will work or not?
https://pipci.jeffgeerling.com/
https://pipci.jeffgeerling.com/cards_network/edup-intel-ax200-wifi-6.html
https://pipci.jeffgeerling.com/cards_network/intel-ax210-wifi-6e.html

What about the Hummingboard with miniPCIe?
https://www.solid-run.com/embedded-industrial-iot/nxp-i-mx6-family/hummingboard/#edge

Thanks again!

**Comment by KuskoSoft** [comment]
Hello @HeyGF ,

I have already tested AX200/AX210 with embedded devices Radxa Rock 3a (http://radxa.com/products/rock3/3a/) and Tinker Board 2 (https://tinker-board.asus.com/series/tinker-board-2.html). 

I think that if your mentioned PCs detect NICs  via PCIe, the FeitCSI should work. So in simple words, if the computers/devices work with other NICs via PCIe the FeitCSI will work with AX200/AX210.

If you try it with other devices, please let me know!

If you have any questions please feel free to ask.

Thanks!

**Comment by NikKonst** [comment]
Hi!

Could you share which OS image you used for testing with the Radxa Rock 3A? I'm trying to install feitcsi-iwlwifi but running into an issue with linux-headers.

> I have already tested AX200/AX210 with embedded devices Radxa Rock 3a (http://radxa.com/products/rock3/3a/) and Tinker Board 2 (https://tinker-board.asus.com/series/tinker-board-2.html).

**Comment by ygtcnclk** [comment]
My Raspberry Pi CM4 can detect AX210 card but I cant use the .deb package installation because it fails like this:

`
Error! Bad return status for module build on kernel: 6.8.0-1031-raspi (aarch64)
Consult /var/lib/dkms/feitcsi-iwlwifi/2.0.0/build/make.log for more information.
dpkg: error processing package feitcsi-iwlwifi (--configure):
 installed feitcsi-iwlwifi package post-installation script subprocess returned error ex
it status 10
Errors were encountered while processing:
 feitcsi-iwlwifi
needrestart is being skipped since dpkg has failed
`

could you help please @KuskoSoft
